"""Circuit Analyzer -- extract features from supported circuit frontends.

This module is the foundation of the EMRG pipeline. It inspects a
Qiskit or Cirq circuit and returns a :class:`CircuitFeatures` dataclass
that downstream modules (heuristics, codegen) consume.

Typical usage::

    from qiskit import QuantumCircuit
    from emrg.analyzer import analyze_circuit

    qc = QuantumCircuit(2, 2)
    qc.h(0)
    qc.cx(0, 1)
    qc.measure_all()

    features = analyze_circuit(qc)
    print(features)
"""

from __future__ import annotations

import math
import warnings
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Mapping

    from qiskit import QuantumCircuit

from emrg.frontends import Frontend, detect_frontend

__all__ = [
    "CircuitFeatures",
    "analyze_circuit",
    "MULTI_QUBIT_GATE_NAMES",
    "CLIFFORD_GATE_NAMES",
    "DEFAULT_MULTI_QUBIT_ERROR_RATE",
    "DEFAULT_SINGLE_QUBIT_ERROR_RATE",
    "NOISE_THRESHOLD_LOW",
    "NOISE_THRESHOLD_MODERATE",
    "PEC_OVERHEAD_NOISE_MULTIPLIER",
    "CDR_NON_CLIFFORD_FRACTION_THRESHOLD",
    "CDR_MIN_DEPTH",
    "CDR_MAX_DEPTH",
]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Gate names that Qiskit uses for two-qubit and multi-qubit operations.
#: Includes 3-qubit gates (ccx, ccz, cswap) that also benefit from
#: multi-qubit error rate estimates.
MULTI_QUBIT_GATE_NAMES: frozenset[str] = frozenset(
    {
        "cx",
        "cz",
        "cy",
        "ch",
        "crx",
        "cry",
        "crz",
        "cp",
        "swap",
        "iswap",
        "ecr",
        "rzx",
        "rzz",
        "rxx",
        "ryy",
        "csx",
        "cu",
        "cu1",
        "cu3",
        "dcx",
        "ccx",  # 3-qubit
        "ccz",  # 3-qubit
        "cswap",  # 3-qubit
    }
)

#: Default proxy for average multi-qubit gate error rate on NISQ hardware.
#: IBM Eagle r3 ~ 0.005-0.01; we use a conservative midpoint.
DEFAULT_MULTI_QUBIT_ERROR_RATE: float = 0.01

#: Default proxy for average single-qubit gate error rate.
DEFAULT_SINGLE_QUBIT_ERROR_RATE: float = 0.001

#: Noise factor below this is classified as "low".
NOISE_THRESHOLD_LOW: float = 0.05

#: Noise factor below this (but >= NOISE_THRESHOLD_LOW) is "moderate";
#: at or above this threshold is "high".
NOISE_THRESHOLD_MODERATE: float = 0.20

#: Multiplier used in the PEC overhead formula:
#: ``exp(PEC_OVERHEAD_NOISE_MULTIPLIER * noise_factor * multi_qubit_gate_count)``.
PEC_OVERHEAD_NOISE_MULTIPLIER: float = 2.0

#: Gate names that are always Clifford (regardless of parameters).
#: The Clifford group is generated by {H, S, CNOT}.
CLIFFORD_GATE_NAMES: frozenset[str] = frozenset(
    {
        "h",
        "x",
        "y",
        "z",
        "s",
        "sdg",
        "sx",
        "sxdg",
        "cx",
        "cz",
        "cy",
        "swap",
        "iswap",
        "id",
        "i",
        "ecr",
        "dcx",
    }
)

#: Rotation gate names that are Clifford only at specific angles
#: (multiples of pi/2).
_ROTATION_GATE_NAMES: frozenset[str] = frozenset(
    {
        "r",
        "rz",
        "ry",
        "rx",
        "p",
        "u1",
        "rxx",
        "ryy",
        "rzz",
        "rzx",
        "crx",
        "cry",
        "crz",
        "cp",
        "u2",
        "u3",
        "u",
        "cu",
        "cu1",
        "cu3",
    }
)

#: Minimum non-Clifford gate fraction for CDR to be considered.
CDR_NON_CLIFFORD_FRACTION_THRESHOLD: float = 0.3

#: Minimum circuit depth for CDR consideration.
CDR_MIN_DEPTH: int = 12

#: Maximum circuit depth for CDR consideration.
CDR_MAX_DEPTH: int = 40


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


def _freeze_dict(value: dict[str, Any]) -> MappingProxyType[str, Any]:
    """Wrap a dict in a read-only ``MappingProxyType``."""
    return MappingProxyType(value)


@dataclass(frozen=True)
class CircuitFeatures:
    """Immutable snapshot of circuit properties relevant to error mitigation.

    All fields are derived from Qiskit introspection -- no simulation needed.

    Attributes:
        num_qubits: Number of quantum bits in the circuit.
        depth: Circuit depth (longest path of dependent operations).
        gate_counts: Read-only mapping of gate name to count
            (e.g. ``{'cx': 4, 'h': 3}``).
        total_gate_count: Total number of gate operations.
        multi_qubit_gate_count: Number of multi-qubit gates (2-qubit and
            3-qubit, e.g. CX, CCX, CSWAP).
        single_qubit_gate_count: Number of single-qubit gates.
        num_parameters: Number of unbound parameters (0 for non-variational).
        has_measurements: Whether the circuit contains measurement operations.
        estimated_noise_factor: Simple heuristic noise proxy
            (``multi_qubit_gate_count * multi_qubit_error_rate
              + single_qubit_gate_count * single_qubit_error_rate``).
        noise_category: Human-readable category: ``"low"``, ``"moderate"``,
            or ``"high"``.
        noise_model_available: Whether a noise model is available for PEC.
            Defaults to ``False``; set to ``True`` when a depolarizing (or
            other) noise model can be supplied so the heuristic engine may
            consider Probabilistic Error Cancellation.
        pec_overhead_estimate: Approximate PEC sampling overhead computed as
            ``exp(2 * noise_factor * multi_qubit_gate_count)``.  Values much
            larger than ~1000 make PEC impractical.
        layer_heterogeneity: Ratio of the maximum to minimum multi-qubit gate
            count across circuit layers (with +1 denominator smoothing).
            Higher values indicate more varied layer structure, which favours
            layerwise noise scaling over uniform folding.  Returns 0.0 when
            the circuit has fewer than two layers containing multi-qubit gates.
        non_clifford_count: Number of non-Clifford gates in the circuit.
            Non-Clifford gates include T, Tdg, and any rotation gate whose
            angle is not a multiple of pi/2.
        non_clifford_fraction: Fraction of gates that are non-Clifford
            (``non_clifford_count / total_gate_count``).  0.0 means all
            Clifford, 1.0 means all non-Clifford.
    """

    num_qubits: int
    depth: int
    gate_counts: Mapping[str, int] = field(default_factory=dict)
    total_gate_count: int = 0
    multi_qubit_gate_count: int = 0
    single_qubit_gate_count: int = 0
    num_parameters: int = 0
    has_measurements: bool = False
    estimated_noise_factor: float = 0.0
    noise_category: str = "low"
    noise_model_available: bool = False
    pec_overhead_estimate: float = 1.0
    layer_heterogeneity: float = 0.0
    non_clifford_count: int = 0
    non_clifford_fraction: float = 0.0


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


def _validate_qiskit_circuit(qc: QuantumCircuit) -> list[str]:
    """Validate the circuit and return a list of warning messages (may be empty).

    Checks:
    - Circuit must be a ``QuantumCircuit`` instance.
    - Circuit must contain at least one gate operation.
    - Circuit should have measurements for meaningful mitigation.

    Raises:
        TypeError: If *qc* is not a ``QuantumCircuit``.
        ValueError: If the circuit has zero gate operations.
    """
    from qiskit import QuantumCircuit as _QuantumCircuit  # lazy runtime import

    if not isinstance(qc, _QuantumCircuit):
        raise TypeError(f"Expected a qiskit.QuantumCircuit, got {type(qc).__name__}.")

    ops = qc.count_ops()
    # Filter out measurement/barrier/delay -- only count real gates
    gate_ops = {
        name: count
        for name, count in ops.items()
        if name not in ("measure", "barrier", "delay", "reset")
    }

    if not gate_ops:
        raise ValueError(
            "Circuit has no gate operations. "
            "Provide a circuit with at least one quantum gate."
        )

    warns: list[str] = []
    if "measure" not in ops:
        warns.append(
            "Circuit has no measurements. Error mitigation requires "
            "measurement results -- consider adding qc.measure_all()."
        )
    if qc.num_parameters > 0:
        warns.append(
            f"Circuit has {qc.num_parameters} unbound parameter(s). "
            "Parameters must be bound before execution "
            "(e.g. qc = qc.assign_parameters({...})). "
            "EMRG will analyze the circuit structure, but the generated "
            "code cannot run until all parameters are resolved."
        )
    return warns


# ---------------------------------------------------------------------------
# Noise estimation
# ---------------------------------------------------------------------------


def _classify_noise(noise_factor: float) -> str:
    """Map a numeric noise factor to a human-readable category.

    Thresholds are deliberately conservative and tunable.
    """
    if noise_factor < NOISE_THRESHOLD_LOW:
        return "low"
    elif noise_factor < NOISE_THRESHOLD_MODERATE:
        return "moderate"
    else:
        return "high"


def _estimate_noise(
    multi_qubit_count: int,
    single_qubit_count: int,
    *,
    multi_qubit_error_rate: float = DEFAULT_MULTI_QUBIT_ERROR_RATE,
    single_qubit_error_rate: float = DEFAULT_SINGLE_QUBIT_ERROR_RATE,
) -> float:
    """Return a simple additive noise proxy.

    This is *not* a rigorous noise model -- it is a fast heuristic used to
    guide mitigation strategy selection.
    """
    return (
        multi_qubit_count * multi_qubit_error_rate
        + single_qubit_count * single_qubit_error_rate
    )


def _estimate_pec_overhead(
    noise_factor: float,
    multi_qubit_gate_count: int,
) -> float:
    """Return the approximate PEC sampling overhead.

    The formula ``exp(2 * noise_factor * multi_qubit_gate_count)`` captures
    the exponential cost that makes PEC impractical for large or very noisy
    circuits.  The exponent is capped at 700 to avoid ``OverflowError`` on
    circuits with hundreds of multi-qubit gates.
    """
    exponent = PEC_OVERHEAD_NOISE_MULTIPLIER * noise_factor * multi_qubit_gate_count
    # math.exp overflows around ~709; cap to prevent OverflowError.
    if exponent > 700:
        return math.inf
    return math.exp(exponent)


# ---------------------------------------------------------------------------
# DAG-derived features
# ---------------------------------------------------------------------------


def _is_clifford_angle(angle: float) -> bool:
    """Return ``True`` if *angle* is a multiple of pi/2 (within tolerance).

    Clifford rotations are those at multiples of pi/2:
    0, pi/2, pi, 3*pi/2, 2*pi, etc.
    """
    units = angle / (math.pi / 2)
    return abs(units - round(units)) < 1e-8


_NON_GATE_OP_NAMES: frozenset[str] = frozenset({"measure", "barrier", "delay", "reset"})


def _walk_qiskit_dag(qc: QuantumCircuit) -> tuple[float, int]:
    """Single DAG pass returning ``(layer_heterogeneity, non_clifford_count)``.

    Building the DAG dominates ``analyze_circuit`` for large circuits, so
    both per-layer statistics and non-Clifford counting share one pass.

    *layer_heterogeneity* is ``max(counts) / (min(counts) + 1)`` over
    circuit layers that contain at least one multi-qubit gate; 0.0 when
    fewer than two such layers exist.

    *non_clifford_count* classifies each op:
    - Gates in ``CLIFFORD_GATE_NAMES`` are always Clifford.
    - ``t``/``tdg`` are always non-Clifford.
    - Rotation gates are Clifford only when all parameters are multiples
      of pi/2.
    - Unknown gates are conservatively counted as non-Clifford.
    """
    from qiskit.converters import circuit_to_dag

    dag = circuit_to_dag(qc)

    mq_counts: list[int] = []
    non_clifford = 0

    for layer_dict in dag.layers():
        layer_dag = layer_dict["graph"]
        mq_in_layer = 0

        for node in layer_dag.op_nodes():
            name = node.op.name
            if name in _NON_GATE_OP_NAMES:
                continue

            if name in MULTI_QUBIT_GATE_NAMES:
                mq_in_layer += 1

            # Clifford classification.
            if name in CLIFFORD_GATE_NAMES:
                continue
            if name in ("t", "tdg"):
                non_clifford += 1
                continue
            if name in _ROTATION_GATE_NAMES:
                params = node.op.params
                if params and all(
                    isinstance(p, (int, float)) and _is_clifford_angle(float(p))
                    for p in params
                ):
                    continue
                non_clifford += 1
                continue
            # Unknown gate -- conservatively non-Clifford.
            non_clifford += 1

        if mq_in_layer > 0:
            mq_counts.append(mq_in_layer)

    if len(mq_counts) < 2:
        layer_het = 0.0
    else:
        layer_het = max(mq_counts) / (min(mq_counts) + 1)

    return layer_het, non_clifford


# ---------------------------------------------------------------------------
# Cirq-derived features
# ---------------------------------------------------------------------------


def _is_cirq_measurement_or_reset(op: Any) -> bool:
    """Return True for Cirq operations that should not count as gates."""
    import cirq

    gate = getattr(op, "gate", None)
    if isinstance(gate, cirq.MeasurementGate):
        return True
    reset_channel = getattr(cirq, "ResetChannel", None)
    return reset_channel is not None and isinstance(gate, reset_channel)


def _cirq_exponent(gate: Any) -> Any:
    """Return a Cirq gate exponent when present."""
    return getattr(gate, "exponent", None)


def _as_float(value: Any) -> float | None:
    """Return *value* as float when it is numeric and resolved."""
    if isinstance(value, (int, float)):
        return float(value)
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _is_half_turn_clifford(exponent: float) -> bool:
    """Return True when a Cirq half-turn exponent is Clifford."""
    units = exponent / 0.5
    return abs(units - round(units)) < 1e-8


def _cirq_gate_name(op: Any) -> str:
    """Return a stable, Qiskit-like gate-count name for common Cirq gates."""
    import cirq

    if isinstance(op, cirq.CircuitOperation):
        return "circuit_operation"

    gate = getattr(op, "gate", None)
    if gate is None:
        return type(op).__name__.lower()

    exponent = _as_float(_cirq_exponent(gate))
    if isinstance(gate, cirq.HPowGate):
        return "h"
    if isinstance(gate, cirq.CNotPowGate):
        return "cx"
    if isinstance(gate, cirq.CZPowGate):
        return "cz"
    if isinstance(gate, cirq.SwapPowGate):
        return "swap"
    if isinstance(gate, cirq.XPowGate):
        if exponent == 1:
            return "x"
        return "rx"
    if isinstance(gate, cirq.YPowGate):
        if exponent == 1:
            return "y"
        return "ry"
    if isinstance(gate, cirq.ZPowGate):
        if exponent == 1:
            return "z"
        if exponent == 0.5:
            return "s"
        if exponent == -0.5:
            return "sdg"
        if exponent == 0.25:
            return "t"
        if exponent == -0.25:
            return "tdg"
        return "rz"

    return type(gate).__name__.lower()


def _is_cirq_non_clifford(op: Any) -> bool:
    """Conservatively classify a Cirq operation as non-Clifford."""
    import cirq

    if _is_cirq_measurement_or_reset(op):
        return False
    if isinstance(op, cirq.CircuitOperation):
        return True

    gate = getattr(op, "gate", None)
    if gate is None:
        return True

    exponent = _cirq_exponent(gate)
    if exponent is not None:
        exponent_float = _as_float(exponent)
        if exponent_float is None:
            return True
        return not _is_half_turn_clifford(exponent_float)

    if isinstance(gate, cirq.IdentityGate):
        return False

    return True


def _cirq_parameter_count(circuit: Any, operations: list[Any]) -> int:
    """Count unique Cirq symbols, falling back to parameterized operations."""
    import cirq

    try:
        return len(cirq.parameter_names(circuit))
    except Exception:
        return sum(1 for op in operations if cirq.is_parameterized(op))


def _cirq_layer_heterogeneity(circuit: Any) -> float:
    """Return Cirq multi-qubit operation heterogeneity across moments."""
    mq_counts: list[int] = []
    for moment in circuit:
        mq_in_moment = sum(
            1
            for op in moment.operations
            if not _is_cirq_measurement_or_reset(op) and len(op.qubits) > 1
        )
        if mq_in_moment > 0:
            mq_counts.append(mq_in_moment)

    if len(mq_counts) < 2:
        return 0.0
    return max(mq_counts) / (min(mq_counts) + 1)


def _validate_cirq_circuit(circuit: Any, operations: list[Any]) -> list[str]:
    """Validate a Cirq circuit and return warning messages."""
    gate_ops = [op for op in operations if not _is_cirq_measurement_or_reset(op)]
    if not gate_ops:
        raise ValueError(
            "Circuit has no gate operations. "
            "Provide a circuit with at least one quantum gate."
        )

    warns: list[str] = []
    if not any(_is_cirq_measurement_or_reset(op) for op in operations):
        warns.append(
            "Circuit has no measurements. Error mitigation requires "
            "measurement results -- consider adding measurements."
        )

    num_parameters = _cirq_parameter_count(circuit, operations)
    if num_parameters > 0:
        warns.append(
            f"Circuit has {num_parameters} unbound parameter(s). "
            "Parameters must be resolved before execution. "
            "EMRG will analyze the circuit structure, but the generated "
            "code cannot run until all parameters are resolved."
        )
    return warns


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def _analyze_qiskit_circuit(
    qc: QuantumCircuit,
    *,
    multi_qubit_error_rate: float = DEFAULT_MULTI_QUBIT_ERROR_RATE,
    single_qubit_error_rate: float = DEFAULT_SINGLE_QUBIT_ERROR_RATE,
    noise_model_available: bool = False,
) -> CircuitFeatures:
    """Analyze a Qiskit ``QuantumCircuit`` with the original native path."""
    warn_msgs = _validate_qiskit_circuit(qc)
    for msg in warn_msgs:
        warnings.warn(msg, UserWarning, stacklevel=2)

    # --- extract raw ops ----------------------------------------------------
    ops = dict(qc.count_ops())  # OrderedDict -> dict

    # Separate gate ops from non-gate ops (measure, barrier, etc.)
    non_gate_names = {"measure", "barrier", "delay", "reset"}
    gate_counts: dict[str, int] = {
        name: count for name, count in ops.items() if name not in non_gate_names
    }

    total_gate_count = sum(gate_counts.values())
    multi_qubit_gate_count = sum(
        count for name, count in gate_counts.items() if name in MULTI_QUBIT_GATE_NAMES
    )
    single_qubit_gate_count = total_gate_count - multi_qubit_gate_count

    # --- noise estimate -----------------------------------------------------
    noise_factor = _estimate_noise(
        multi_qubit_gate_count,
        single_qubit_gate_count,
        multi_qubit_error_rate=multi_qubit_error_rate,
        single_qubit_error_rate=single_qubit_error_rate,
    )

    pec_overhead = _estimate_pec_overhead(noise_factor, multi_qubit_gate_count)
    layer_het, non_clifford = _walk_qiskit_dag(qc)
    nc_fraction = non_clifford / total_gate_count if total_gate_count > 0 else 0.0

    return CircuitFeatures(
        num_qubits=qc.num_qubits,
        depth=qc.depth(),
        gate_counts=_freeze_dict(gate_counts),
        total_gate_count=total_gate_count,
        multi_qubit_gate_count=multi_qubit_gate_count,
        single_qubit_gate_count=single_qubit_gate_count,
        num_parameters=qc.num_parameters,
        has_measurements="measure" in ops,
        estimated_noise_factor=round(noise_factor, 6),
        noise_category=_classify_noise(noise_factor),
        noise_model_available=noise_model_available,
        pec_overhead_estimate=round(pec_overhead, 6),
        layer_heterogeneity=round(layer_het, 4),
        non_clifford_count=non_clifford,
        non_clifford_fraction=round(nc_fraction, 6),
    )


def _analyze_cirq_circuit(
    circuit: Any,
    *,
    multi_qubit_error_rate: float = DEFAULT_MULTI_QUBIT_ERROR_RATE,
    single_qubit_error_rate: float = DEFAULT_SINGLE_QUBIT_ERROR_RATE,
    noise_model_available: bool = False,
) -> CircuitFeatures:
    """Analyze a Cirq ``Circuit`` into EMRG's shared feature model."""
    operations = list(circuit.all_operations())
    warn_msgs = _validate_cirq_circuit(circuit, operations)
    for msg in warn_msgs:
        warnings.warn(msg, UserWarning, stacklevel=2)

    gate_ops = [op for op in operations if not _is_cirq_measurement_or_reset(op)]
    gate_counts: dict[str, int] = {}
    for op in gate_ops:
        name = _cirq_gate_name(op)
        gate_counts[name] = gate_counts.get(name, 0) + 1

    total_gate_count = len(gate_ops)
    multi_qubit_gate_count = sum(1 for op in gate_ops if len(op.qubits) > 1)
    single_qubit_gate_count = sum(1 for op in gate_ops if len(op.qubits) == 1)
    num_parameters = _cirq_parameter_count(circuit, operations)

    noise_factor = _estimate_noise(
        multi_qubit_gate_count,
        single_qubit_gate_count,
        multi_qubit_error_rate=multi_qubit_error_rate,
        single_qubit_error_rate=single_qubit_error_rate,
    )

    pec_overhead = _estimate_pec_overhead(noise_factor, multi_qubit_gate_count)
    layer_het = _cirq_layer_heterogeneity(circuit)
    non_clifford = sum(1 for op in gate_ops if _is_cirq_non_clifford(op))
    nc_fraction = non_clifford / total_gate_count if total_gate_count > 0 else 0.0

    return CircuitFeatures(
        num_qubits=len(circuit.all_qubits()),
        depth=len(circuit),
        gate_counts=_freeze_dict(gate_counts),
        total_gate_count=total_gate_count,
        multi_qubit_gate_count=multi_qubit_gate_count,
        single_qubit_gate_count=single_qubit_gate_count,
        num_parameters=num_parameters,
        has_measurements=any(_is_cirq_measurement_or_reset(op) for op in operations),
        estimated_noise_factor=round(noise_factor, 6),
        noise_category=_classify_noise(noise_factor),
        noise_model_available=noise_model_available,
        pec_overhead_estimate=round(pec_overhead, 6),
        layer_heterogeneity=round(layer_het, 4),
        non_clifford_count=non_clifford,
        non_clifford_fraction=round(nc_fraction, 6),
    )


def analyze_circuit(
    circuit: object,
    *,
    frontend: str | Frontend | None = None,
    multi_qubit_error_rate: float = DEFAULT_MULTI_QUBIT_ERROR_RATE,
    single_qubit_error_rate: float = DEFAULT_SINGLE_QUBIT_ERROR_RATE,
    noise_model_available: bool = False,
) -> CircuitFeatures:
    """Analyze a supported circuit and extract mitigation-relevant features.

    Parameters
    ----------
    circuit:
        A Qiskit ``QuantumCircuit`` or Cirq ``Circuit`` to analyze.
    frontend:
        Optional explicit frontend: ``"qiskit"`` or ``"cirq"``. When omitted,
        EMRG auto-detects Qiskit first, then Cirq.
    multi_qubit_error_rate:
        Proxy error rate for multi-qubit gates (default 0.01).
    single_qubit_error_rate:
        Proxy error rate for single-qubit gates (default 0.001).
    noise_model_available:
        Whether a noise model is available for techniques like PEC
        (default ``False``).  Set to ``True`` when a depolarizing or
        tomographic noise model can be supplied.

    Returns
    -------
    CircuitFeatures
        Immutable dataclass with extracted metrics.

    Raises
    ------
    TypeError
        If *circuit* is not a supported circuit type, or if an explicit
        frontend does not match the circuit object.
    ValueError
        If the circuit has zero gate operations.

    Examples
    --------
    >>> from qiskit import QuantumCircuit
    >>> qc = QuantumCircuit(2, 2); _ = qc.h(0); _ = qc.cx(0, 1)
    >>> qc.measure([0, 1], [0, 1])
    >>> features = analyze_circuit(qc)
    >>> features.num_qubits
    2
    >>> features.multi_qubit_gate_count
    1
    """
    active_frontend = detect_frontend(circuit, frontend)
    if active_frontend is Frontend.QISKIT:
        return _analyze_qiskit_circuit(
            circuit,
            multi_qubit_error_rate=multi_qubit_error_rate,
            single_qubit_error_rate=single_qubit_error_rate,
            noise_model_available=noise_model_available,
        )
    if active_frontend is Frontend.CIRQ:
        return _analyze_cirq_circuit(
            circuit,
            multi_qubit_error_rate=multi_qubit_error_rate,
            single_qubit_error_rate=single_qubit_error_rate,
            noise_model_available=noise_model_available,
        )
    raise TypeError(f"Unsupported frontend: {active_frontend!r}.")
